angular.module('ettersending.directives', [
	'ettersending.services',
	'nav.cmstekster',
	'nav.feilmeldinger',
	'nav.markup',
	'nav.fremdriftsindikator',
	'nav.validering',
	'nav.stickybunn',
	'nav.hjelpetekst',
	'nav.sidetittel',
	'nav.bildenavigering',
	'nav.scroll.directive',
	'nav.skjematittel',
	'nav.aria',
	'nav.norskDatoFilter',
    'nav.fokus',
    'nav.bildelastet',
    'nav.nowrap'
]);
