/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

object Versions {
    const val ktlint = "0.45.2"
    const val logback = "1.2.11"
    const val logstash = "7.2"
    const val log4j = "2.19.0"
}

plugins {
    kotlin("jvm") version "1.7.22"
    kotlin("plugin.spring") version "1.7.22"
    id("org.springframework.boot") version "2.7.7"
    id("com.github.ben-manes.versions") version "0.44.0" // ./gradlew dependencyUpdates
    id("org.jlleitschuh.gradle.ktlint") version "11.0.0"
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

ktlint {
    this.version.set(Versions.ktlint)
}

val githubUser: String by project
val githubPassword: String by project

repositories {
    mavenCentral()
    maven("https://plugins.gradle.org/m2/")
    maven("https://repo.spring.io/plugins-release/")
    maven {
        url = uri("https://maven.pkg.github.com/navikt/sosialhjelp-common")
        credentials {
            username = githubUser
            password = githubPassword
        }
    }
}

dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-slf4j:1.6.4")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-reactor:1.6.4")
    implementation("no.nav.sbl.dialogarena:soknadsosialhjelp-filformat:1.2022.12.22-12.23-e5a89d40cc3c")
    implementation("no.nav.sosialhjelp:sosialhjelp-common-api:1.20221108.1040-97f1b80")
    implementation("no.nav.sosialhjelp:sosialhjelp-common-selftest:1.20221108.1040-97f1b80")
    implementation("org.springframework.boot:spring-boot-starter-jetty:2.7.8")
    implementation("org.springframework.boot:spring-boot-starter-webflux:2.7.8")
    implementation("org.springframework.boot:spring-boot-starter-logging:2.7.8")
    implementation("org.springframework.boot:spring-boot-starter-validation:2.7.8")
    implementation("org.springframework.boot:spring-boot-starter-jdbc:2.7.8")
    implementation("org.springframework.boot:spring-boot-starter-actuator:2.7.8")
    implementation("org.springframework:spring-beans:5.3.25")
    implementation("org.springframework:spring-context:5.3.25")
    implementation("org.springframework:spring-core:5.3.25")
    implementation("org.springframework:spring-web:5.3.25")
    implementation("org.springframework:spring-webflux:5.3.25")
    implementation("org.springframework:spring-tx:5.3.25")
    implementation("org.springframework:spring-jdbc:5.3.25")
    implementation("org.springdoc:springdoc-openapi-ui:1.6.14")
    implementation("org.springdoc:springdoc-openapi-kotlin:1.6.14")
    implementation("io.projectreactor.netty:reactor-netty-http:1.1.2")
    implementation("jakarta.activation:jakarta.activation-api:1.2.2")
    implementation("jakarta.annotation:jakarta.annotation-api:1.3.5")
    implementation("jakarta.servlet:jakarta.servlet-api:4.0.4")
    implementation("jakarta.xml.bind:jakarta.xml.bind-api:2.3.3")
    implementation("jakarta.inject:jakarta.inject-api:1.0.5")
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.14.1")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.14.1")
    implementation("com.fasterxml.jackson.core:jackson-core:2.14.1")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.14.1")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.14.1")
    implementation("org.flywaydb:flyway-core:9.12.0")
    implementation("com.auth0:java-jwt:4.2.2")
    implementation("io.lettuce:lettuce-core:6.2.2.RELEASE")
    implementation("no.ks.fiks:kryptering:1.3.1")
    implementation("no.ks.fiks.svarut:svarut-rest-klient:1.2.0")
    implementation("ch.qos.logback:logback-classic:1.2.11")
    implementation("ch.qos.logback:logback-core:1.2.11")
    implementation("io.prometheus:simpleclient:0.16.0")
    implementation("io.micrometer:micrometer-registry-prometheus:1.10.3")
    implementation("no.nav.security:token-validation-spring:2.1.9")
    implementation("org.apache.pdfbox:pdfbox:2.0.27")
    implementation("org.apache.pdfbox:jempbox:1.8.17")
    implementation("com.vdurmont:emoji-java:5.1.1")
    implementation("org.apache.commons:commons-text:1.10.0")
    implementation("commons-codec:commons-codec:1.15")
    implementation("com.migesok:jaxb-java-time-adapters:1.1.3")
    implementation("org.apache.tika:tika-core:2.6.0")
    implementation("no.finn.unleash:unleash-client-java:3.3.4")
    implementation("org.apache.pdfbox:preflight:2.0.27")

    //    Logging
    implementation("ch.qos.logback:logback-classic:${Versions.logback}")
    implementation("net.logstash.logback:logstash-logback-encoder:${Versions.logstash}")

    runtimeOnly("org.springframework:spring-aop:5.3.25")
    runtimeOnly("jakarta.validation:jakarta.validation-api:2.0.2")
    runtimeOnly("com.oracle.database.jdbc:ojdbc10:19.17.0.0")
    runtimeOnly("org.hsqldb:hsqldb:2.7.1")
    runtimeOnly("net.logstash.logback:logstash-logback-encoder:7.2")
    runtimeOnly("org.glassfish.jaxb:jaxb-runtime:2.3.7")
    runtimeOnly("org.slf4j:slf4j-api:1.7.36")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.7.8")
    testImplementation("no.nav.security:token-validation-spring-test:2.1.9")
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")
    testImplementation("org.springframework:spring-test:5.3.25")
    testImplementation("io.mockk:mockk:1.13.3")
    testImplementation("io.mockk:mockk-jvm:1.13.3")

    constraints {
        implementation("org.apache.logging.log4j:log4j-api:${Versions.log4j}") {
            because("0-day exploit i version 2.0.0-2.14.1")
        }
        implementation("org.apache.logging.log4j:log4j-to-slf4j:${Versions.log4j}") {
            because("0-day exploit i version 2.0.0-2.14.1")
        }
        implementation("org.slf4j:slf4j-api") {
            version { strictly("1.7.36") }
            because("Trenger versjon høyere enn 1.7.6")
        }
    }
}

group = "no.nav.sosialhjelp"
version = "18.1.0-SNAPSHOT"
description = "sosialhjelp-soknad-api"

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.getByName<org.springframework.boot.gradle.tasks.bundling.BootJar>("bootJar") {
    this.archiveFileName.set("app.jar")
}
