server:
  servlet:
    context-path: '/sosialhjelp/soknad-api'
  shutdown: graceful
  max-http-request-header-size: 16KB

spring:
  servlet:
    multipart:
      max-file-size: 100MB

digisos:
  cache:
    kodeverk:
      time-to-live: 86400

token_exchange_endpoint: ${NAIS_TOKEN_EXCHANGE_ENDPOINT}
token_endpoint: ${NAIS_TOKEN_ENDPOINT}

springdoc:
  api-docs:
    enabled: true
