name: "Create tag and release image"
description: "Create and release tag, create and release docker image"

inputs:
  github-token:
    required: true
    description: "Github TOKEN for this workflow"
outputs:
  artifact-version:
    description: Created artifact version
    value: ${{ steps.artifact-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Create and release tag
      id: artifact-version
      uses: navikt/sosialhjelp-ci/actions/create-and-release-tag@master

    - name: Build and push docker image
      uses: navikt/sosialhjelp-ci/actions/build-and-push-docker-image@master
      with:
        image-name: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}
        github-token: ${{ inputs.github-token }}
        artifact-version: ${{ steps.artifact-version.outputs.artifact-version }}