CREATE TABLE SOKNADUNDERARBEID (
    ID NUMERIC NOT NULL,
    BEHANDLINGSID VARCHAR2(255 CHAR) NOT NULL,
    TILKNYTTETBEHANDLINGSID VARCHAR2(255 CHAR),
    EIER VARCHAR2(255 CHAR) NOT NULL,
    DATA BLOB,
    ORGNR VARCHAR2(255 CHAR),
    STATUS VARCHAR2(255 CHAR),
    OPPRETTETDATO TIMESTAMP,
    SISTENDRETDATO TIMESTAMP
);

CREATE INDEX INDEX_SOKNADUA_ID ON SOKNADUNDERARBEID(ID);
CREATE INDEX INDEX_SOKNADUA_BEHID ON SOKNADUNDERARBEID(BEHANDLINGSID);

CREATE sequence SOKNADUA_ID_SEQ start WITH 1 increment BY 1;