CREATE TABLE VEDLEGGSTATUS(
    ID NUMERIC NOT NULL,
    BEHANDLINGSID VARCHAR2(255 CHAR) NOT NULL,
    EIER VARCHAR2(255 CHAR) NOT NULL,
    STATUS VARCHAR2(255 CHAR) NOT NULL,
    TYPE VARCHAR2(255 CHAR) NOT NULL
);

CREATE INDEX INDEX_VEDLEGGSTATUS_ID ON VEDLEGGSTATUS(ID);
CREATE INDEX INDEX_VEDLEGGSTATUS_BEHID ON VEDLEGGSTATUS(BEHANDLINGSID);