CREATE TABLE VEDLEGGSTATUS(
    VEDLEGGSTATUSID NUMERIC NOT NULL,
    BEHANDLINGSID VARCHAR2(255 CHAR) NOT NULL,
    EIER VARCHAR2(255 CHAR) NOT NULL,
    STATUS VARCHAR2(255 CHAR) NOT NULL,
    TYPE VARCHAR2(255 CHAR) NOT NULL,
    SENDTSOKNADID NUMERIC NOT NULL,
    CONSTRAINT VEDLEGGSTATUS_PK PRIMARY KEY (VEDLEGGSTATUSID),
    CONSTRAINT VEDLEGGSTATUS_FK FOREIGN KEY (SENDTSOKNADID) REFERENCES SENDTSOKNAD(SENDTSOKNADID)
);

CREATE INDEX INDEX_VEDLEGGSTATUS_ID ON VEDLEGGSTATUS(VEDLEGGSTATUSID);
CREATE INDEX INDEX_VEDLEGGSTATUS_BEHID ON VEDLEGGSTATUS(BEHANDLINGSID);