CREATE TABLE SENDT_SOKNAD (
    SENDT_SOKNAD_ID NUMBER(19, 0) NOT NULL,
    BEHANDLINGSID VARCHAR2(255 CHAR) NOT NULL,
    TILKNYTTETBEHANDLINGSID VARCHAR2(255 CHAR),
    EIER VARCHAR2(255 CHAR) NOT NULL,
    FIKSFORSENDELSEID VARCHAR2(255 CHAR) NOT NULL,
    BRUKEROPPRETTETDATO TIMESTAMP(3) DEFAULT SYSDATE NOT NULL,
    BRUKERFERDIGDATO TIMESTAMP(3) DEFAULT SYSDATE NOT NULL,
    SENDTDATO TIMESTAMP(3) DEFAULT SYSDATE NOT NULL,
    CONSTRAINT UNIK_BEHANDLINGSID UNIQUE (BEHANDLINGSID),
    CONSTRAINT UNIK_FIKSFORSENDELSEID UNIQUE (FIKSFORSENDELSEID),
    CONSTRAINT SENDT_SOKNAD_PK PRIMARY KEY (SENDT_SOKNADID)
);

CREATE INDEX INDEX_SENDTSOKNAD_BEHID ON SENDT_SOKNAD(BEHANDLINGSID);
CREATE INDEX INDEX_SENDTSOKNAD_TILKNBEHID ON SENDT_SOKNAD(TILKNYTTETBEHANDLINGSID);
CREATE INDEX INDEX_SENDTSOKNAD_EIER ON SENDT_SOKNAD(EIER);
CREATE INDEX INDEX_SENDTSOKNAD_FIKSID ON SENDT_SOKNAD(FIKSFORSENDELSEID);
CREATE INDEX INDEX_SENDTSOKNAD_OPPR ON SENDT_SOKNAD(BRUKEROPPRETTETDATO);
CREATE INDEX INDEX_SENDTSOKNAD_FERDIG ON SENDT_SOKNAD(BRUKERFERDIGDATO);
CREATE INDEX INDEX_SENDTSOKNAD_SENDT ON SENDT_SOKNAD(SENDTDATO);

CREATE sequence SENDT_SOKNAD_ID_SEQ start WITH 1 increment BY 1;