CREATE TABLE VEDLEGGSTATUS(
    VEDLEGGSTATUSID NUMBER(19, 0) NOT NULL,
    EIER VARCHAR2(255 CHAR) NOT NULL,
    STATUS VARCHAR2(255 CHAR) NOT NULL,
    TYPE VARCHAR2(255 CHAR) NOT NULL,
    SENDTSOKNADID NUMBER(19, 0) NOT NULL,
    CONSTRAINT UNIK_IDTYPE UNIQUE (SENDTSOKNADID, TYPE),
    CONSTRAINT VEDLEGGSTATUS_PK PRIMARY KEY (VEDLEGGSTATUSID),
    CONSTRAINT VEDLEGGSTATUS_FK FOREIGN KEY (SENDTSOKNADID) REFERENCES SENDTSOKNAD(SENDTSOKNADID)
);

CREATE INDEX INDEX_VEDLEGGSTATUS_ID ON VEDLEGGSTATUS(VEDLEGGSTATUSID);
CREATE INDEX INDEX_VEDLEGGSTATUS_SENDTSOKNADID ON VEDLEGGSTATUS(SENDTSOKNADID);

CREATE sequence VEDLEGGSTATUSID_SEQ start WITH 1 increment BY 1;