CREATE TABLE SOKNADUNDERARBEID (
    SOKNADUAID NUMERIC NOT NULL,
    BEHANDLINGSID VARCHAR2(255 CHAR) NOT NULL,
    TILKNYTTETBEHANDLINGSID VARCHAR2(255 CHAR),
    EIER VARCHAR2(255 CHAR) NOT NULL,
    DATA BLOB,
    ORGNR VARCHAR2(255 CHAR),
    STATUS VARCHAR2(255 CHAR),
    OPPRETTETDATO TIMESTAMP,
    SISTENDRETDATO TIMESTAMP,
    CONSTRAINT UNIK_BEHANDLINGSID UNIQUE (BEHANDLINGSID),
    CONSTRAINT SOKNADUNDERARBEID_PK PRIMARY KEY (SOKNADUAID)
);

CREATE INDEX INDEX_SOKNADUA_ID ON SOKNADUNDERARBEID(SOKNADUAID);
CREATE INDEX INDEX_SOKNADUA_BEHID ON SOKNADUNDERARBEID(BEHANDLINGSID);
CREATE INDEX INDEX_SOKNADUA_TILKNBEHID ON SOKNADUNDERARBEID(TILKNYTTETBEHANDLINGSID);
CREATE INDEX INDEX_SOKNADUA_EIER ON SOKNADUNDERARBEID(EIER);
CREATE INDEX INDEX_SOKNADUA_OPPR ON SOKNADUNDERARBEID(STATUS, OPPRETTETDATO);
CREATE INDEX INDEX_SOKNADUA_ENDR ON SOKNADUNDERARBEID(STATUS, SISTENDRETDATO);

CREATE sequence SOKNADUA_ID_SEQ start WITH 1 increment BY 1;