CREATE TABLE OPPLASTETVEDLEGG(
    ID NUMERIC NOT NULL,
    BEHANDLINGSID VARCHAR2(255 CHAR) NOT NULL,
    EIER VARCHAR2(255 CHAR) NOT NULL,
    TYPE VARCHAR2(255 CHAR) NOT NULL,
    DATA blob
);

CREATE INDEX INDEX_OPPLASTETVEDLEGG_ID ON OPPLASTETVEDLEGG(ID);
CREATE INDEX INDEX_OPPLASTETVEDLEGG_BEHID ON OPPLASTETVEDLEGG(BEHANDLINGSID);