CREATE TABLE SOKNADUNDERARBEID (
    SOKNADUAID NUMBER(19, 0) NOT NULL,
    VERSJON NUMBER(19, 0) DEFAULT 1,
    BEHANDLINGSID VARCHAR2(255 CHAR) NOT NULL,
    TILKNYTTETBEHANDLINGSID VARCHAR2(255 CHAR),
    EIER VARCHAR2(255 CHAR) NOT NULL,
    DATA BLOB NOT NULL,
    ORGNR VARCHAR2(255 CHAR) NOT NULL,
    STATUS VARCHAR2(255 CHAR) NOT NULL,
    OPPRETTETDATO TIMESTAMP(3) DEFAULT SYSDATE NOT NULL,
    SISTENDRETDATO TIMESTAMP(3) DEFAULT SYSDATE NOT NULL,
    CONSTRAINT UNIK_BEHANDLINGSID UNIQUE (BEHANDLINGSID),
    CONSTRAINT SOKNADUNDERARBEID_PK PRIMARY KEY (SOKNADUAID)
);

CREATE INDEX INDEX_SOKNADUA_ID ON SOKNADUNDERARBEID(SOKNADUAID);
CREATE INDEX INDEX_SOKNADUA_BEHID ON SOKNADUNDERARBEID(BEHANDLINGSID);
CREATE INDEX INDEX_SOKNADUA_TILKNBEHID ON SOKNADUNDERARBEID(TILKNYTTETBEHANDLINGSID);
CREATE INDEX INDEX_SOKNADUA_EIER ON SOKNADUNDERARBEID(EIER);
CREATE INDEX INDEX_SOKNADUA_OPPR ON SOKNADUNDERARBEID(STATUS, OPPRETTETDATO);
CREATE INDEX INDEX_SOKNADUA_ENDR ON SOKNADUNDERARBEID(STATUS, SISTENDRETDATO);

CREATE sequence SOKNADUAID_SEQ start WITH 1 increment BY 1;