CREATE TABLE OPPLASTETVEDLEGG(
    UUID VARCHAR2(255 CHAR) NOT NULL,
    BEHANDLINGSID VARCHAR2(255 CHAR) NOT NULL,
    EIER VARCHAR2(255 CHAR) NOT NULL,
    TYPE VARCHAR2(255 CHAR) NOT NULL,
    DATA blob,
    SOKNADUAID NUMERIC NOT NULL,
    CONSTRAINT OPPLASTETVEDLEGG_FK FOREIGN KEY (SOKNADUAID) REFERENCES SOKNADUNDERARBEID(SOKNADUAID),
    CONSTRAINT UNIK_UUID UNIQUE (UUID)
);

CREATE INDEX INDEX_OPPLASTETVEDLEGG_BEHID ON OPPLASTETVEDLEGG(BEHANDLINGSID);