CREATE TABLE SENDTSOKNAD (
    SENDTSOKNADID NUMBER(19, 0) NOT NULL,
    BEHANDLINGSID VARCHAR2(255 CHAR) NOT NULL,
    TILKNYTTETBEHANDLINGSID VARCHAR2(255 CHAR),
    EIER VARCHAR2(255 CHAR) NOT NULL,
    FIKSFORSENDELSEID VARCHAR2(255 CHAR) NOT NULL,
    BRUKEROPPRETTETDATO TIMESTAMP(3) DEFAULT SYSDATE NOT NULL,
    BRUKERFERDIGDATO TIMESTAMP(3) DEFAULT SYSDATE NOT NULL,
    SENDTDATO TIMESTAMP(3) DEFAULT SYSDATE NOT NULL,
    CONSTRAINT UNIK_BEHANDLINGSID UNIQUE (BEHANDLINGSID),
    CONSTRAINT UNIK_FIKSFORSENDELSEID UNIQUE (FIKSFORSENDELSEID),
    CONSTRAINT SENDTSOKNAD_PK PRIMARY KEY (SENDTSOKNADID)
);

CREATE INDEX INDEX_SENDTSOKNAD_ID ON SENDTSOKNAD(SENDTSOKNADID);
CREATE INDEX INDEX_SENDTSOKNAD_BEHID ON SENDTSOKNAD(BEHANDLINGSID);
CREATE INDEX INDEX_SENDTSOKNAD_TILKNBEHID ON SENDTSOKNAD(TILKNYTTETBEHANDLINGSID);
CREATE INDEX INDEX_SENDTSOKNAD_EIER ON SENDTSOKNAD(EIER);
CREATE INDEX INDEX_SENDTSOKNAD_FIKSID ON SENDTSOKNAD(FIKSFORSENDELSEID);
CREATE INDEX INDEX_SENDTSOKNAD_OPPR ON SENDTSOKNAD(BRUKEROPPRETTETDATO);
CREATE INDEX INDEX_SENDTSOKNAD_FERDIG ON SENDTSOKNAD(BRUKERFERDIGDATO);
CREATE INDEX INDEX_SENDTSOKNAD_SENDT ON SENDTSOKNAD(SENDTDATO);

CREATE sequence SENDTSOKNADID_SEQ start WITH 1 increment BY 1;