CREATE TABLE VEDLEGGSTATUS(
    VEDLEGGSTATUS_ID NUMBER(19, 0) NOT NULL,
    EIER VARCHAR2(255 CHAR) NOT NULL,
    STATUS VARCHAR2(255 CHAR) NOT NULL,
    TYPE VARCHAR2(255 CHAR) NOT NULL,
    SENDT_SOKNAD_ID NUMBER(19, 0) NOT NULL,
    CONSTRAINT UNIK_IDTYPE UNIQUE (SENDT_SOKNAD_ID, TYPE),
    CONSTRAINT VEDLEGGSTATUS_PK PRIMARY KEY (VEDLEGGSTATUS_ID),
    CONSTRAINT VEDLEGGSTATUS_FK FOREIGN KEY (SENDT_SOKNAD_ID) REFERENCES SENDT_SOKNAD(SENDT_SOKNAD_ID)
);

CREATE INDEX INDEX_VEDLSTATUS_SENDTSOKNADID ON VEDLEGGSTATUS(SENDT_SOKNAD_ID);

CREATE sequence VEDLEGGSTATUSID_SEQ start WITH 1 increment BY 1;