CREATE TABLE SENDTSOKNAD (
    SENDTSOKNADID NUMERIC NOT NULL,
    BEHANDLINGSID VARCHAR2(255 CHAR) NOT NULL,
    TILKNYTTETBEHANDLINGSID VARCHAR2(255 CHAR),
    EIER VARCHAR2(255 CHAR) NOT NULL,
    FIKSFORSENDELSEID VARCHAR2(255 CHAR),
    OPPRETTETDATO TIMESTAMP,
    SENDTDATO TIMESTAMP,
    CONSTRAINT SENDTSOKNAD_PK PRIMARY KEY (SENDTSOKNADID)
);

CREATE INDEX INDEX_SENDTSOKNAD_ID ON SENDTSOKNAD(SENDTSOKNADID);
CREATE INDEX INDEX_SENDTSOKNAD_BEHID ON SENDTSOKNAD(BEHANDLINGSID);
CREATE INDEX INDEX_SENDTSOKNAD_TILKNBEHID ON SENDTSOKNAD(TILKNYTTETBEHANDLINGSID);
CREATE INDEX INDEX_SENDTSOKNAD_EIER ON SENDTSOKNAD(EIER);
CREATE INDEX INDEX_SENDTSOKNAD_FIKSID ON SENDTSOKNAD(FIKSFORSENDELSEID);

CREATE sequence SENDTSOKNAD_ID_SEQ start WITH 1 increment BY 1;