CREATE TABLE SENDTSOKNAD (
    ID NUMERIC NOT NULL,
    BEHANDLINGSID VARCHAR2(255 CHAR) NOT NULL,
    TILKNYTTETBEHANDLINGSID VARCHAR2(255 CHAR),
    EIER VARCHAR2(255 CHAR) NOT NULL,
    FIKSFORSENDELSEID VARCHAR2(255 CHAR),
    OPPRETTETDATO TIMESTAMP,
    SENDTDATO TIMESTAMP
);

CREATE INDEX INDEX_SENDTSOKNAD_ID ON SENDTSOKNAD(ID);
CREATE INDEX INDEX_SENDTSOKNAD_BEHID ON SENDTSOKNAD(BEHANDLINGSID);

CREATE sequence SENDTSOKNAD_ID_SEQ start WITH 1 increment BY 1;