package no.nav.sbl.dialogarena.person;

public enum Adressetype {
    BOSTEDSADRESSE, POSTADRESSE, GATEADRESSE, POSTBOKSADRESSE, OMRAADEADRESSE, UTENLANDSK_ADRESSE, UKJENT_ADRESSE, MIDLERTIDIG_POSTADRESSE_NORGE, MIDLERTIDIG_POSTADRESSE_UTLAND
}
