'use strict';
angular.module('app.controllers', [
    'app.services',
    'nav.reellarbeidssoker',
    'nav.ytelser',
    'nav.egennaering',
    'nav.verneplikt',
    'nav.utdanning',
    'nav.vedlegg.controller',
    'nav.opplasting.controller',
    'nav.barnetillegg',
    'nav.barn',
    'nav.vedlegg.controller',
    'nav.forsettsenere',
    'nav.dagpenger',
    'nav.arbeidsforhold',
    'nav.informasjonsside',
    'nav.behandlingside',
    'nav.personalia',
    'nav.oppsummering',
    'nav.adresse',
    'nav.arbeidsforhold',
    'nav.informasjonsside',
    'nav.behandlingside',
    'nav.avbryt',
    'nav.bekreftelse'
]);
