'use strict';
angular.module('app.directives', [
	'app.services',
	'nav.booleanradio',
	'nav.cmstekster',
	'nav.input',
	'nav.feilmeldinger',
	'nav.stickyFeilmelding',
	'nav.sporsmalferdig',
	'nav.markup',
	'nav.stegindikator',
	'nav.textarea',
	'nav.fremdriftsindikator',
	'nav.validering',
    'nav.stickybunn',
	'nav.select',
	'nav.hjelpetekst',
	'nav.datepicker',
	'nav.prosent',
	'nav.ingenytelser',
	'nav.sidetittel',
    'nav.apneaccordion',
    'nav.bildenavigering',
    'nav.accordion'
]);
