package no.nav.sbl.dialogarena.soknadinnsending.business.person;

public enum Adressetype {
    POSTADRESSE_UTLAND,
    BOSTEDSADRESSE, POSTADRESSE,
    GATEADRESSE, POSTBOKSADRESSE,
    OMRAADEADRESSE, UTENLANDSK_ADRESSE,
    UKJENT_ADRESSE, MIDLERTIDIG_POSTADRESSE_NORGE,
    MIDLERTIDIG_POSTADRESSE_UTLAND
}
