CREATE TABLE HENDELSE(
    BEHANDLINGSID VARCHAR2(255 CHAR) NOT NULL,
    HENDELSE_TYPE VARCHAR2(255 CHAR) NOT NULL,
    HENDELSE_TIDSPUNKT TIMESTAMP(6) DEFAULT SYSDATE,
    VERSJON int,
    SKJEMANUMMER VARCHAR2(255 CHAR)
);

CREATE INDEX INDEX_HENDELSE_BEHID on HENDELSE(BEHANDLINGSID);