CREATE TABLE FILLAGER(
    BEHANDLINGSID VARCHAR2(255 CHAR) NOT NULL,
    UUID VARCHAR2(255 CHAR) NOT NULL,
    EIER VARCHAR2(255 CHAR) NOT NULL,
    DATA blob,
);

CREATE INDEX INDEX_FILLAGER_BEHID on FILLAGER(BEHANDLINGSID);
CREATE INDEX INDEX_FILLAGER_UUID on FILLAGER(UUID);