apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{applicationName}}
  namespace: {{namespace}}
  labels:
    team: teamdigisos
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "150M"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /sosialhjelp/soknad-api/internal/isAlive
    initialDelay: 60
    timeout: 1
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/soknad-api/internal/isAlive
    initialDelay: 60
    timeout: 1
  prometheus:
    enabled: {{prometheusEnabled}}
    path: /sosialhjelp/soknad-api/internal/metrics
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
  webproxy: {{webProxyEnabled}}
{{#if azureEnabled}}
  azure:
    application:
      enabled: {{azureEnabled}}
{{/if}}
{{#if maskinportenEnabled}}
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "skatteetaten:inntekt"
        - name: "ks:fiks"
{{/if}}
{{#if vaultEnabled}}
  vault:
    enabled: true
    paths:
{{#each kvPaths}}
      - mountPath: {{@key}}
        kvPath: {{this}}
{{/each}}
{{/if}}
  tokenx:
    enabled: {{tokenXEnabled}}
  accessPolicy:
{{#if tokenXEnabled}}
    inbound:
      rules:
        - application: mine-saker-api
          namespace: personbruker
          cluster: {{personbrukerGcpCluster}}
        - application: mine-saker-api
          namespace: min-side
          cluster: {{personbrukerGcpCluster}}
        - application: {{sosialhjelpDialogApi}}
          cluster: {{dialogGcpCluster}}
{{/if}}
    outbound:
      external:
      {{#each outboundExternalHosts}}
        - host: "{{this}}"
      {{else}}
        []
      {{/each}}
      rules:
      {{#if hasOutboundRulesGcpApplications}}
      {{#each outboundRulesGcpApplications}}
        - application: "{{this}}"
      {{else}}
        []
      {{/each}}
      {{#unless isMock}}
        - application: clamav
          namespace: clamav
      {{/unless}}
      {{/if}}
      {{#unless isMock}}
      {{#each outboundRulesFssApplications}}
        - application: "{{this}}"
          cluster: {{fssCluster}}
      {{else}}
        []
      {{/each}}
      {{/unless}}
  ingresses:
{{#each ingresses}}
    - "{{this}}"
{{/each}}
  leaderElection: {{leaderElectionEnabled}}
  resources:
    limits:
      cpu: {{cpuLimit}}
      memory: {{memoryLimit}}
    requests:
      cpu: {{cpuRequest}}
      memory: {{memoryRequest}}
  env:
{{#each env}}
    - name: {{@key}}
      value: "{{this}}"
{{/each}}
  envFrom:
    - configmap: loginservice-idporten
{{#each envsecret}}
    - secret: "{{this}}"
{{/each}}
