apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{applicationName}}
  namespace: {{namespace}}
  labels:
    team: teamdigisos
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "150M"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /sosialhjelp/soknad-api/internal/isAlive
    initialDelay: 60
    timeout: 1
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/soknad-api/internal/isAlive
    initialDelay: 60
    timeout: 1
  prometheus:
    enabled: {{prometheusEnabled}}
    path: /sosialhjelp/soknad-api/internal/metrics
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
  webproxy: {{webProxyEnabled}}
{{#if maskinportenEnabled}}
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "skatteetaten:inntekt"
{{/if}}
{{#if vaultEnabled}}
  vault:
    enabled: true
    paths:
{{#each kvPaths}}
      - mountPath: {{@key}}
        kvPath: {{this}}
{{/each}}
{{/if}}
  tokenx:
    enabled: {{tokenXEnabled}}
  accessPolicy:
{{#if tokenXEnabled}}
    inbound:
      rules:
        - application: mine-saker-api
          namespace: personbruker
          cluster: {{personbrukerGcpCluster}}
        - application: sosialhjelp-dialog-api
          cluster: {{dialogGcpCluster}}
{{/if}}
{{#if isGcp}}
    outbound:
      external:
        - host: "digisos-gcp.dev.nav.no"
        - host: "digisos.labs.nais.io"
        - host: "unleash.nais.io"
      rules:
        - application: sosialhjelp-mock-alt-api
        - application: sosialhjelp-soknad-api-redis
{{/if}}
{{#if isGcp}}
  filesFrom:
    - secret: virksomhetssertifikat
{{/if}}
  ingresses:
{{#each ingresses}}
    - "{{this}}"
{{/each}}
  leaderElection: {{leaderElectionEnabled}}
  resources:
    limits:
      cpu: {{cpuLimit}}
      memory: {{memoryLimit}}
    requests:
      cpu: {{cpuRequest}}
      memory: {{memoryRequest}}
  env:
{{#each env}}
    - name: {{@key}}
      value: "{{this}}"
{{/each}}
  envFrom:
    - configmap: loginservice-idporten
{{#each envsecret}}
    - secret: "{{this}}"
{{/each}}
