angular.module('nav.arbeidsforhold',
    [
        'nav.arbeidsforhold.controller',
        'nav.arbeidsforhold.nyttarbeidsforhold.controller',
        'nav.arbeidsforhold.permitteringpopup',
        'nav.arbeidsforhold.turnus.directive',
        'nav.arbeidsforhold.grensearbeid.directive',
        'nav.nyearbeidsforhold.directive',
        'nav.arbeidsforhold.directive'
    ]);
