CREATE TABLE OPPGAVE
(
    ID              NUMERIC NOT NULL,
    BEHANDLINGSID   VARCHAR(255),
    TYPE            VARCHAR(255),
    STATUS          VARCHAR(255),
    STEG            NUMERIC,
    OPPGAVEDATA     CLOB,
    OPPGAVERESULTAT CLOB,
    OPPRETTET       TIMESTAMP,
    SISTKJORT       TIMESTAMP,
    NESTEFORSOK     TIMESTAMP,
    RETRIES         NUMERIC,
    CONSTRAINT UNIK_ID UNIQUE (ID)
);

CREATE INDEX INDEX_STATUS_FORSOK_ID ON OPPGAVE (STATUS, NESTEFORSOK);

CREATE SEQUENCE OPPGAVE_ID_SEQ START WITH 1 INCREMENT BY 1;