CREATE TABLE SOKNAD_UNDER_ARBEID
(
    SOKNAD_UNDER_ARBEID_ID  NUMBER(19, 0) NOT NULL,
    VERSJON                 NUMBER(19, 0) DEFAULT 1 NOT NULL,
    BEHANDLINGSID           VARCHAR2(255 CHAR) NOT NULL,
    TILKNYTTETBEHANDLINGSID VARCHAR2(255 CHAR),
    EIER                    VARCHAR2(255 CHAR) NOT NULL,
    DATA                    BLOB,
    STATUS                  VARCHAR2(255 CHAR) NOT NULL,
    OPPRETTETDATO           TIMESTAMP(3) DEFAULT SYSDATE NOT NULL,
    SISTENDRETDATO          TIMESTAMP(3) DEFAULT SYSDATE NOT NULL,
    CONSTRAINT UNIK_UA_BEHANDLINGSID UNIQUE (BEHANDLINGSID),
    CONSTRAINT SOKNAD_UNDER_ARBEID_PK PRIMARY KEY (SOKNAD_UNDER_ARBEID_ID)
);

CREATE INDEX INDEX_SOKNADUA_TILKNBEHID ON SOKNAD_UNDER_ARBEID (TILKNYTTETBEHANDLINGSID);
CREATE INDEX INDEX_SOKNADUA_EIER ON SOKNAD_UNDER_ARBEID (EIER);
CREATE INDEX INDEX_SOKNADUA_OPPR ON SOKNAD_UNDER_ARBEID (STATUS, OPPRETTETDATO);
CREATE INDEX INDEX_SOKNADUA_ENDR ON SOKNAD_UNDER_ARBEID (STATUS, SISTENDRETDATO);

CREATE sequence SOKNAD_UNDER_ARBEID_ID_SEQ START WITH 1 INCREMENT BY 1;