CREATE TABLE SOKNADMETADATA
(
    ID                      NUMERIC      NOT NULL,
    BEHANDLINGSID           VARCHAR(255) NOT NULL,
    TILKNYTTETBEHANDLINGSID VARCHAR(255),
    SKJEMA                  VARCHAR(255),
    FNR                     VARCHAR(255),
    HOVEDSKJEMA             CLOB,
    VEDLEGG                 CLOB,
    ORGNR                   VARCHAR(255),
    NAVENHET                VARCHAR(255),
    FIKSFORSENDELSEID       VARCHAR(255),
    SOKNADTYPE              VARCHAR(255),
    INNSENDINGSTATUS        VARCHAR(255),
    OPPRETTETDATO           TIMESTAMP,
    SISTENDRETDATO          TIMESTAMP,
    INNSENDTDATO            TIMESTAMP,
    BATCHSTATUS             VARCHAR(255) DEFAULT 'LEDIG' NOT NULL,
    LEST_DITT_NAV           NUMBER(1,0) DEFAULT 0 NOT NULL
);

CREATE INDEX INDEX_METADATA_ID ON SOKNADMETADATA (ID);
CREATE INDEX INDEX_METADATA_BEHID ON SOKNADMETADATA (BEHANDLINGSID);
CREATE INDEX INDEX_TILKNYTTET_ID ON SOKNADMETADATA(TILKNYTTETBEHANDLINGSID);

CREATE SEQUENCE METADATA_ID_SEQ START WITH 1 INCREMENT BY 1;