CREATE TABLE OPPLASTET_VEDLEGG
(
    UUID                   VARCHAR2(255 CHAR) NOT NULL,
    EIER                   VARCHAR2(255 CHAR) NOT NULL,
    TYPE                   VARCHAR2(255 CHAR) NOT NULL,
    DATA                   BLOB NOT NULL,
    SOKNAD_UNDER_ARBEID_ID NUMBER(19, 0) NOT NULL,
    FILNAVN                VARCHAR2(255 CHAR) NOT NULL,
    SHA512                 VARCHAR2(255 CHAR) NOT NULL,
    CONSTRAINT OPPLASTET_VEDLEGG_FK FOREIGN KEY (SOKNAD_UNDER_ARBEID_ID) REFERENCES SOKNAD_UNDER_ARBEID (SOKNAD_UNDER_ARBEID_ID),
    CONSTRAINT UNIK_OPPLASTET_VEDLEGG_UUID UNIQUE (UUID)
);

CREATE INDEX INDEX_OPPLVEDL_SOKNADUAID ON OPPLASTET_VEDLEGG (SOKNAD_UNDER_ARBEID_ID);