name: "Determine tag version"
description: "Determine tag version based on branch"

runs:
  using: "composite"
  steps:
    - name: "Version for master"
      if: github.ref_name == 'master'
      id: version-master
      uses: navikt/sosialhjelp-ci/actions/create-artifact-version@master

    - name: "Write master-version to branch"
      if: github.ref_name == 'master'
      run: |
        echo "VERSION=${{ steps.version-master.outputs.artifact-version }}" >> $GITHUB_ENV
      shell: bash

    - name: "Version for branch"
      if: github.ref_name != 'master'
      id: version-fb
      uses: navikt/sosialhjelp-ci/actions/create-and-release-tag@master
      with:
        prefix: ${{ github.ref_name }}_

    - name: "Write FB-version to branch"
      if: github.ref_name != 'master'
      run: |
        echo "VERSION=${{ steps.version-fb.outputs.artifact-version }}" >> $GITHUB_ENV
      shell: bash