apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-soknad-api-mock
  namespace: teamdigisos
  labels:
    team: teamdigisos
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "150M"
    nais.io/run-as-user: "1001"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /sosialhjelp/soknad-api/internal/isAlive
    initialDelay: 60
    timeout: 1
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/soknad-api/internal/isAlive
    initialDelay: 60
    timeout: 1
  prometheus:
    enabled: false
  replicas:
    min: 1
    max: 1
  webproxy: false
  accessPolicy:
    outbound:
      external:
        - host: "digisos.ekstern.dev.nav.no"
        - host: "teamdigisos-unleash-api.nav.cloud.nais.io"
      rules:
        - application: sosialhjelp-mock-alt-api-mock
        - application: sosialhjelp-konvertering-til-pdf
  ingresses:
    - "https://digisos.ekstern.dev.nav.no/sosialhjelp/soknad-api"
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 512Mi
  envFrom:
    - configmap: loginservice-idporten
    - secret: sosialhjelp-soknad-api-unleash-api-token
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: "mock-alt,log-kibana,no-redis"
    - name: PORT
      value: "8080"
    - name: AAREG_URL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/aareg"
    - name: AZURE_OPENID_CONFIG_TOKEN_ENDPOINT
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/azuretoken/azuread"
    - name: UTBETALDATA_API_BASEURL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api"
    - name: PDL_API_URL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/pdl_endpoint_url"
    - name: UNLEASH_ENV
      value: "mock"
    - name: EREG_URL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/ereg"
    - name: DIGISOS_API_BASEURL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/fiks/"
    - name: KODEVERK_URL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/kodeverk"
    - name: KONTOREGISTER_API_BASEURL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api"
    - name: KRR_URL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/krr/"
    - name: LOGINSERVICE_URL
      value: "https://digisos.ekstern.dev.nav.no/sosialhjelp/mock-alt/login"
    - name: MASKINPORTEN_WELL_KNOWN_URL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/well-known/maskinporten"
    - name: OIDC_ISSUER_SELVBETJENING_DISCOVERYURL
      value: "https://digisos.ekstern.dev.nav.no/sosialhjelp/mock-alt-api/well-known/selvbetjening"
    - name: NORG_URL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/norg_endpoint_url"
    - name: SOKNAD_BOSTOTTE_URL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/husbanken"
    - name: SKATTEETATEN_API_BASEURL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/skatteetaten/"
    - name: TOKEN_X_WELL_KNOWN_URL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/well-known/tokenx"
    - name: NEDETID_START
      value: ""
    - name: NEDETID_SLUTT
      value: ""
    - name: ENVIRONMENT_NAME
      value: "mock"
    - name: GOTENBERG_URL
      value: "http://sosialhjelp-konvertering-til-pdf/"
