apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{applicationName}}
  namespace: {{namespace}}
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /sosialhjelp/soknad-api/internal/isAlive
    initialDelay: 60
    timeout: 1
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/soknad-api/internal/isAlive
    initialDelay: 60
    timeout: 1
  prometheus:
    enabled: {{prometheusEnabled}}
    path: /sosialhjelp/soknad-api/internal/metrics
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
  webproxy: true
  vault:
    enabled: {{vaultEnabled}}
{{#if vaultEnabled}}
    paths:
{{#each kvPaths}}
      - mountPath: {{@key}}
        kvPath: {{this}}
{{/each}}
{{/if}}
  ingresses:
{{#each ingresses}}
    - "{{this}}"
{{/each}}
  resources:
    limits:
      cpu: 3000m
      memory: {{memoryLimit}}
    requests:
      cpu: 200m
      memory: {{memoryRequest}}
  env:
{{#each env}}
    - name: {{@key}}
      value: "{{this}}"
{{/each}}
  envFrom:
    - configmap: loginservice-idporten
{{#unless isRedisMocked}}
    - secret: redis-password-soknad-api
{{/unless}}
