apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-soknad-api
  namespace: digisos
  labels:
    team: digisos
spec:
  image: docker.pkg.github.com/navikt/sosialhjelp-soknad-api/sosialhjelp-soknad-api:{{version}}
  port: 8080
  liveness:
    path: /sosialhjelp/soknad-api/internal/isAlive
    initialDelay: 60
    timeout: 1
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/soknad-api/internal/isAlive
    initialDelay: 60
    timeout: 1
  replicas:
    min: 1
    max: 2
  ingresses:
    - "https://sosialhjelp-soknad-api.dev-nav.no"
  resources:
    limits:
      cpu: 3000m
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 2Gi
  env:
    - name: FASIT_ENVIRONMENT_NAME
      value: q0
    - name: TILLATMOCK
      value: "true"
    - name: START_NORG_WITHMOCK
      value: "true"
    - name: MAIN_CLASS
      value: "no.nav.sbl.dialogarena.mock.MockSoknadsosialhjelpServer"
    - name: dockerWithDefaultMockActivated
      value: "true"
    - name: HEROKU
      value: "true"
    - name: PORT
      value: "8080"
