apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-soknad-api-temp
  namespace: {{namespace}}
  labels:
    team: digisos
spec:
  image: docker.pkg.github.com/navikt/sosialhjelp-soknad-api/sosialhjelp-soknad-api:{{version}}
  port: 8080
  liveness:
    path: /soknadsosialhjelp-server/internal/isAlive
    initialDelay: 60
    timeout: 1
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    path: /soknadsosialhjelp-server/internal/isAlive
    initialDelay: 60
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  replicas:
    min: 2
    max: 2
  webproxy: true
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/datasource
        kvPath: {{datasourceKvPath}}
  ingresses:
{{#each ingresses}}
    - "{{this}}"
{{/each}}
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      memory: 2Gi
  env:
    - name: FASIT_ENVIRONMENT_NAME
      value: {{namespace}}
{{#each env}}
    - name: {{@key}}
      value: "{{this}}"
{{/each}}
