apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-soknad-api
  namespace: {{namespace}}
  labels:
    team: teamdigisos
spec:
  image: docker.pkg.github.com/navikt/sosialhjelp-soknad-api/sosialhjelp-soknad-api:{{version}}
  port: 8080
  liveness:
    path: /sosialhjelp/soknad-api/internal/isAlive
    initialDelay: 60
    timeout: 1
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/soknad-api/internal/isAlive
    initialDelay: 60
    timeout: 1
  prometheus:
    enabled: {{prometheusEnabled}}
    path: /prometheus
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
  webproxy: true
  vault:
    enabled: {{vaultEnabled}}
{{#if vaultEnabled}}
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: {{vaultKvPath}}
      - mountPath: /var/run/secrets/datasource
        kvPath: {{datasourceKvPath}}
      - mountPath: /var/run/secrets/nais.io/virksomhetssertifikat
        kvPath: {{virksomhetssertifikatKvPath}}
{{/if}}
  ingresses:
{{#each ingresses}}
    - "{{this}}"
{{/each}}
  resources:
    limits:
      cpu: 3000m
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 2Gi
  env:
{{#each env}}
    - name: {{@key}}
      value: "{{this}}"
{{/each}}
